export const ERROR_CODES = {
  // Auth errors
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NO_WALLET: 'USER_NO_WALLET',

  // Raid errors
  RAID_NOT_FOUND: 'RAID_NOT_FOUND',
  RAID_NOT_ACTIVE: 'RAID_NOT_ACTIVE',
  RAID_ALREADY_COMPLETED: 'RAID_ALREADY_COMPLETED',
  RAID_NOT_PARTICIPANT: 'RAID_NOT_PARTICIPANT',
  RAID_NOT_LEADER: 'RAID_NOT_LEADER',

  // Auction errors
  AUCTION_NOT_FOUND: 'AUCTION_NOT_FOUND',
  AUCTION_NOT_ACTIVE: 'AUCTION_NOT_ACTIVE',
  AUCTION_ENDED: 'AUCTION_ENDED',
  AUCTION_ALREADY_ACTIVE: 'AUCTION_ALREADY_ACTIVE',

  // Bid errors
  BID_TOO_LOW: 'BID_TOO_LOW',
  BID_EXCEEDS_MAX: 'BID_EXCEEDS_MAX',
  BID_INSUFFICIENT_BALANCE: 'BID_INSUFFICIENT_BALANCE',
  BID_ALREADY_WINNING: 'BID_ALREADY_WINNING',
  BID_RATE_LIMITED: 'BID_RATE_LIMITED',

  // Wallet errors
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_MINIMUM_DEPOSIT: 'WALLET_MINIMUM_DEPOSIT',
  WALLET_MINIMUM_WITHDRAWAL: 'WALLET_MINIMUM_WITHDRAWAL',
  WALLET_MAXIMUM_WITHDRAWAL: 'WALLET_MAXIMUM_WITHDRAWAL',
  WALLET_PENDING_WITHDRAWAL: 'WALLET_PENDING_WITHDRAWAL',

  // Coinbase errors
  COINBASE_CHARGE_FAILED: 'COINBASE_CHARGE_FAILED',
  COINBASE_WEBHOOK_INVALID: 'COINBASE_WEBHOOK_INVALID',

  // Distribution errors
  DISTRIBUTION_NO_POT: 'DISTRIBUTION_NO_POT',
  DISTRIBUTION_NO_PARTICIPANTS: 'DISTRIBUTION_NO_PARTICIPANTS',
  DISTRIBUTION_ALREADY_DONE: 'DISTRIBUTION_ALREADY_DONE',

  // General errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: unknown;
}

export class AppError extends Error {
  constructor(
    public code: ErrorCode,
    message: string,
    public statusCode: number = 400,
    public details?: unknown
  ) {
    super(message);
    this.name = 'AppError';
  }

  toJSON(): ApiError {
    return {
      code: this.code,
      message: this.message,
      details: this.details,
    };
  }
}
