import { useRef } from 'react';
import { formatGold } from '@gdkp/shared';
import { Download, Copy, Check, Crown, Trophy, Coins } from 'lucide-react';
import { useState } from 'react';

interface ItemWon {
  id: string;
  name: string;
  icon_url: string | null;
  winner_name: string;
  final_bid: number;
  quality?: number;
}

interface ParticipantPayout {
  user_id: string;
  display_name: string;
  role: string;
  payout_amount: number;
  share_percentage: number;
}

interface RaidSummaryData {
  raid_id: string;
  raid_name: string;
  instance: string;
  leader_name: string;
  pot_total: number;
  leader_cut_percent: number;
  leader_cut_amount: number;
  distributed_amount: number;
  participant_count: number;
  participants: ParticipantPayout[];
  items: ItemWon[];
  completed_at: string;
}

interface RaidSummaryProps {
  data: RaidSummaryData;
  onClose?: () => void;
}

export function RaidSummary({ data, onClose }: RaidSummaryProps) {
  const [copied, setCopied] = useState(false);
  const summaryRef = useRef<HTMLDivElement>(null);

  const generateTextSummary = () => {
    const lines = [
      `═══════════════════════════════════════════`,
      `GDKP RAID SUMMARY - ${data.raid_name}`,
      `═══════════════════════════════════════════`,
      `Instance: ${data.instance}`,
      `Leader: ${data.leader_name}`,
      `Date: ${new Date(data.completed_at).toLocaleDateString('sv-SE')}`,
      ``,
      `─── POT BREAKDOWN ───`,
      `Total Pot: ${data.pot_total}g`,
      `Management Cut: ${data.leader_cut_amount}g (${data.leader_cut_percent}%)`,
      `Distributed: ${data.distributed_amount}g`,
      `Players: ${data.participant_count}`,
      ``,
      `─── PAYOUTS ───`,
      ...data.participants.map(p =>
        `${p.role === 'LEADER' ? '👑 ' : '   '}${p.display_name.padEnd(20)} ${String(p.payout_amount).padStart(8)}g (${p.share_percentage.toFixed(1)}%)`
      ),
      ``,
      `─── ITEMS SOLD ───`,
      ...data.items.map(item =>
        `[${item.name}] → ${item.winner_name} for ${item.final_bid}g`
      ),
      ``,
      `═══════════════════════════════════════════`,
      `Generated by GDKP Platform`,
    ];
    return lines.join('\n');
  };

  const generateCSV = () => {
    const headers = ['Type', 'Name', 'Amount', 'Details'];
    const rows = [
      headers.join(','),
      `"Raid","${data.raid_name}","${data.pot_total}","${data.instance}"`,
      `"Management Cut","${data.leader_name}","${data.leader_cut_amount}","${data.leader_cut_percent}%"`,
      `"Distributed","","${data.distributed_amount}","${data.participant_count} players"`,
      '',
      '"--- Payouts ---","","",""',
      ...data.participants.map(p =>
        `"Payout","${p.display_name}","${p.payout_amount}","${p.share_percentage.toFixed(1)}%"`
      ),
      '',
      '"--- Items ---","","",""',
      ...data.items.map(item =>
        `"Item","${item.name}","${item.final_bid}","Won by ${item.winner_name}"`
      ),
    ];
    return rows.join('\n');
  };

  const handleCopyText = async () => {
    const text = generateTextSummary();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadCSV = () => {
    const csv = generateCSV();
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gdkp-${data.raid_name.toLowerCase().replace(/\s+/g, '-')}-${new Date(data.completed_at).toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    const text = generateTextSummary();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gdkp-${data.raid_name.toLowerCase().replace(/\s+/g, '-')}-${new Date(data.completed_at).toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-gray-900 border border-amber-500/50 rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="bg-gradient-to-r from-amber-900/50 to-amber-800/30 p-4 border-b border-amber-500/30">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-xl font-bold text-amber-400">{data.raid_name}</h2>
              <p className="text-gray-400 text-sm">{data.instance} • {new Date(data.completed_at).toLocaleDateString('sv-SE')}</p>
            </div>
            <div className="flex items-center space-x-2">
              <button
                onClick={handleCopyText}
                className="flex items-center space-x-1 bg-gray-700 hover:bg-gray-600 text-white px-3 py-1.5 rounded text-sm transition-colors"
                title="Copy to clipboard"
              >
                {copied ? <Check className="h-4 w-4 text-green-400" /> : <Copy className="h-4 w-4" />}
                <span>{copied ? 'Copied!' : 'Copy'}</span>
              </button>
              <button
                onClick={handleDownloadText}
                className="flex items-center space-x-1 bg-gray-700 hover:bg-gray-600 text-white px-3 py-1.5 rounded text-sm transition-colors"
                title="Download as text"
              >
                <Download className="h-4 w-4" />
                <span>.txt</span>
              </button>
              <button
                onClick={handleDownloadCSV}
                className="flex items-center space-x-1 bg-amber-600 hover:bg-amber-700 text-white px-3 py-1.5 rounded text-sm transition-colors"
                title="Download as CSV"
              >
                <Download className="h-4 w-4" />
                <span>.csv</span>
              </button>
            </div>
          </div>
        </div>

        <div ref={summaryRef} className="p-4 space-y-4">
          {/* Pot Summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="bg-gray-800 rounded-lg p-3 text-center">
              <Coins className="h-5 w-5 text-amber-500 mx-auto mb-1" />
              <p className="text-xs text-gray-400">Total Pot</p>
              <p className="text-lg font-bold text-amber-400">{formatGold(data.pot_total)}</p>
            </div>
            <div className="bg-gray-800 rounded-lg p-3 text-center">
              <Crown className="h-5 w-5 text-amber-500 mx-auto mb-1" />
              <p className="text-xs text-gray-400">Management Cut ({data.leader_cut_percent}%)</p>
              <p className="text-lg font-bold text-amber-400">{formatGold(data.leader_cut_amount)}</p>
            </div>
            <div className="bg-gray-800 rounded-lg p-3 text-center">
              <Trophy className="h-5 w-5 text-green-500 mx-auto mb-1" />
              <p className="text-xs text-gray-400">Distributed</p>
              <p className="text-lg font-bold text-green-400">{formatGold(data.distributed_amount)}</p>
            </div>
            <div className="bg-gray-800 rounded-lg p-3 text-center">
              <p className="text-2xl mb-1">👥</p>
              <p className="text-xs text-gray-400">Players</p>
              <p className="text-lg font-bold text-white">{data.participant_count}</p>
            </div>
          </div>

          {/* Payouts Table */}
          <div className="bg-gray-800 rounded-lg overflow-hidden">
            <div className="bg-gray-900 px-4 py-2 border-b border-gray-700">
              <h3 className="text-sm font-semibold text-amber-400 uppercase tracking-wide">Payouts</h3>
            </div>
            <div className="divide-y divide-gray-700">
              {data.participants.map((p) => (
                <div key={p.user_id} className="flex items-center justify-between px-4 py-2 hover:bg-gray-700/50">
                  <div className="flex items-center space-x-2">
                    {p.role === 'LEADER' && <Crown className="h-4 w-4 text-amber-500" />}
                    <span className="text-white">{p.display_name}</span>
                    <span className="text-gray-500 text-xs">({p.share_percentage.toFixed(1)}%)</span>
                  </div>
                  <span className="text-amber-400 font-medium">{formatGold(p.payout_amount)}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Items Sold */}
          {data.items.length > 0 && (
            <div className="bg-gray-800 rounded-lg overflow-hidden">
              <div className="bg-gray-900 px-4 py-2 border-b border-gray-700">
                <h3 className="text-sm font-semibold text-amber-400 uppercase tracking-wide">Items Sold ({data.items.length})</h3>
              </div>
              <div className="divide-y divide-gray-700 max-h-60 overflow-y-auto">
                {data.items.map((item) => (
                  <div key={item.id} className="flex items-center justify-between px-4 py-2 hover:bg-gray-700/50">
                    <div className="flex items-center space-x-3">
                      {item.icon_url ? (
                        <img src={item.icon_url} alt="" className="w-8 h-8 rounded border border-purple-500" />
                      ) : (
                        <div className="w-8 h-8 rounded bg-gray-700 border border-purple-500" />
                      )}
                      <div>
                        <p className="text-purple-400 font-medium text-sm">{item.name}</p>
                        <p className="text-gray-500 text-xs">→ {item.winner_name}</p>
                      </div>
                    </div>
                    <span className="text-amber-400 font-medium">{formatGold(item.final_bid)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="border-t border-gray-700 p-4 flex justify-end">
          {onClose && (
            <button
              onClick={onClose}
              className="bg-gray-700 hover:bg-gray-600 text-white px-6 py-2 rounded-lg transition-colors"
            >
              Close
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
